// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrna1YZWZDcMV7qMGpzoD3LV3U71LQF1U',
    appId: '1:605178977326:web:faba4f112f08f6f63513bf',
    messagingSenderId: '605178977326',
    projectId: 'agence-immobiliere-app-c40f9',
    authDomain: 'agence-immobiliere-app-c40f9.firebaseapp.com',
    storageBucket: 'agence-immobiliere-app-c40f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvDM2NAHdbiCXfaG3pPpCS8rMbQVTp74',
    appId: '1:605178977326:android:0eb4fcecc54347f23513bf',
    messagingSenderId: '605178977326',
    projectId: 'agence-immobiliere-app-c40f9',
    storageBucket: 'agence-immobiliere-app-c40f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyA6LtZOTEAs3usD9y5yk-Nw0ppgaDtD8',
    appId: '1:605178977326:ios:eeda94946d16edc53513bf',
    messagingSenderId: '605178977326',
    projectId: 'agence-immobiliere-app-c40f9',
    storageBucket: 'agence-immobiliere-app-c40f9.appspot.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyA6LtZOTEAs3usD9y5yk-Nw0ppgaDtD8',
    appId: '1:605178977326:ios:0ddb0d805de2d2dd3513bf',
    messagingSenderId: '605178977326',
    projectId: 'agence-immobiliere-app-c40f9',
    storageBucket: 'agence-immobiliere-app-c40f9.appspot.com',
    iosBundleId: 'com.example.adminApp.RunnerTests',
  );
}
